# Copyright 2022 GlobalFoundries PDK Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: pcells regression

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  nfet_03v3_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: nfet_03v3 pcells regression
        run: |
          make test-nfet_03v3-pcells

  nfet_05v0_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: nfet_05v0 pcells regression
        run: |
          make test-nfet_05v0-pcells

  nfet_06v0_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: nfet_06v0 pcells regression
        run: |
          make test-nfet_06v0-pcells

  pfet_03v3_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: pfet_03v3 pcells regression
        run: |
          make test-pfet_03v3-pcells

  pfet_05v0_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: pfet_05v0 pcells regression
        run: |
          make test-pfet_05v0-pcells

  pfet_06v0_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: pfet_06v0 pcells regression
        run: |
          make test-pfet_06v0-pcells

  diode_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: diode pcells regression
        run: |
          make test-diode-pcells

  mimcap_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: mimcap pcells regression
        run: |
          make test-mimcap-pcells

  moscap_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: moscap pcells regression
        run: |
          make test-moscap-pcells

  res_pcells_testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: res pcells regression
        run: |
          make test-res-pcells
      
      